# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghost < Formula
  desc "https://github.com/ghost-language/ghost."
  homepage ""
  version "0.15.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ghost-language/ghost/releases/download/v0.15.0/ghost_0.15.0_darwin_amd64.tar.gz"
    sha256 "b0d79869f43ada48590067cebe36d93cfee9f1b584aac18466063710613bc317"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ghost-language/ghost/releases/download/v0.15.0/ghost_0.15.0_darwin_arm64.tar.gz"
    sha256 "feb987e1d86d1774b848826bb512b0192a11570ac4dbf69adb5602f63605a5fc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ghost-language/ghost/releases/download/v0.15.0/ghost_0.15.0_linux_amd64.tar.gz"
    sha256 "4fd1437c1728e22f7664e72053b223feb0b804333912a6769031ac5e5d6bde11"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ghost-language/ghost/releases/download/v0.15.0/ghost_0.15.0_linux_armv6.tar.gz"
    sha256 "c9aff3bd0a6f73af203a06c538f68935408ffcbd6e7bbf87201dd275373efbad"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ghost-language/ghost/releases/download/v0.15.0/ghost_0.15.0_linux_arm64.tar.gz"
    sha256 "05707cd8a951d06fa77121905b3a296836b433c97a3d2b4d663ef6265088d6cd"
  end

  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "ghost"
  end
end
