# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghost < Formula
  desc "https://github.com/ghost-language/ghost."
  homepage ""
  version "1.0.0-beta.2"

  depends_on "git"
  depends_on "zsh"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghost-language/ghost/releases/download/v1.0.0-beta.2/ghost_1.0.0-beta.2_darwin_arm64.tar.gz"
      sha256 "9329c0c170d4db8d5b260a51d6f41821e6a8cbed51cf8361138fbffe62633c18"

      def install
        bin.install "ghost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghost-language/ghost/releases/download/v1.0.0-beta.2/ghost_1.0.0-beta.2_darwin_amd64.tar.gz"
      sha256 "a8a7114d139b357568247f74fd6180c289ad709cfc38ac74c20386412211acd9"

      def install
        bin.install "ghost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ghost-language/ghost/releases/download/v1.0.0-beta.2/ghost_1.0.0-beta.2_linux_armv6.tar.gz"
      sha256 "7c29d85826dc9ca74300c802c6e8521cec5c6c15b5e6e9e989b3b099ecd365bb"

      def install
        bin.install "ghost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghost-language/ghost/releases/download/v1.0.0-beta.2/ghost_1.0.0-beta.2_linux_arm64.tar.gz"
      sha256 "50150ed3e524c967194327c292452aa1ea215a5aa06ab21ab3f3750db5a4f9b0"

      def install
        bin.install "ghost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghost-language/ghost/releases/download/v1.0.0-beta.2/ghost_1.0.0-beta.2_linux_amd64.tar.gz"
      sha256 "d65c24353782515962deab21d2867209a632b37eecadac648c47d3c16c69d9b8"

      def install
        bin.install "ghost"
      end
    end
  end
end
