# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghost < Formula
  desc "https://github.com/ghost-language/ghost."
  homepage ""
  version "0.16.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghost-language/ghost/releases/download/v0.16.0/ghost_0.16.0_darwin_amd64.tar.gz"
      sha256 "f34494b1d926d0d26e9f31bbaed98d9a57c190c5c643dbbc7680887db5efc183"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghost-language/ghost/releases/download/v0.16.0/ghost_0.16.0_darwin_arm64.tar.gz"
      sha256 "84199e0d53343ead5bc9a5bbe1974fbf6c78659f17951fb492a41b7b4ff98660"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ghost-language/ghost/releases/download/v0.16.0/ghost_0.16.0_linux_amd64.tar.gz"
      sha256 "fd22f10dec6dc1b04dcd7546b3d14922efb85357aac8eb3d6941aec54862b6ae"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ghost-language/ghost/releases/download/v0.16.0/ghost_0.16.0_linux_armv6.tar.gz"
      sha256 "18ea9dd7881c0b735898802165a5969145b730ec5b5361d92913133a86127c1b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghost-language/ghost/releases/download/v0.16.0/ghost_0.16.0_linux_arm64.tar.gz"
      sha256 "b7088f3637f71dae9b1a581b3a88f55717b771d7266621ad98de24684f0df4cd"
    end
  end

  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "ghost"
  end
end
